# ===========================================================================
# Project:   DeviceHub
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => ['sproutcore', 'sproutcore/table']
proxy '/devices', :to => 'localhost:3000'
proxy '/packets', :to => 'localhost:3000'