# ===========================================================================
# Project:   DeviceHub
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => [:sproutcore, 'sproutcore/table']
proxy '/devices.json', :to => 'localhost:3000'
proxy '/packets.json', :to => 'localhost:3000'