# ===========================================================================
# Project:   DeviceHub
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore
proxy '/devices.json', :to => 'localhost:3000'